name: Cypress Tests

on:
  push:

  workflow_dispatch:

jobs:
  cypress-chrome-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2.8.2
        with:
          build: npm install
          command: npm run cy:chrome:ci
          group: 'UI - Chrome'
      - name: preview screenhots when failed
        uses: actions/upload-artifact@v2-preview
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots/* 