name: Production Suite

on:
  schedule:
    - cron: '0 6 * * *'

  workflow_dispatch:

jobs:
  cypress-chrome-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Set Suite Type
        run: node setSuiteType.js devSmoke

      - name: Cypress run
        uses: cypress-io/github-action@v2.8.2
        with:
          command: npm run cy:chrome:ci:rec
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Merge JSON reports
        if: always()
        run: node mergeJsonReports.js

      - name: Send merged report to webhook
        if: always()
        run: >
          curl -X POST -H "Content-Type: multipart/form-data" -F "file=@mochawesome-report/mergedReport.json" https://hook.eu1.make.com/6soj6gh8vvfnqpoji3cnp1b5ap8bysf0

      - name: Store merged report as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-merged-report
          path: mochawesome-report/mergedReport.json

      - name: Preview screenshots when failed
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots/*
